---
version: "3.8"

services:
  backend:
    build: .
    container_name: ${PROJECT_NAME}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT_NAME}.rule=Host(`${SECOND_LEVEL_DOMAIN}.localhost`)"
    networks:
      - "traefik-global-proxy"

networks:
  traefik-global-proxy:
    external: true
