---
version: "3.8"

services:
  nginx:
    image: docker.io/nginx
    container_name: ${PROJECT_NAME}
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
      - ${HTML_PATH}:/var/www/html:ro

networks:
  traefik-global-proxy:
    external: true
