---
version: "3.8"

services:
  backend:
    build: .
    container_name: ${PROJECT_NAME}
    labels:
      - "traefik.enable=true"
    networks:
      - "traefik-global-proxy"

networks:
  traefik-global-proxy:
    external: true
