---
version: "3.8"

services:
  backend:
    image: bitnami/nginx
    volumes:
      - ./html:/app
    expose:
      - "8080"
    container_name: ${PROJECT_NAME}
    labels:
      - "traefik.enable=true"
