---
version: "3.8"

services:
  backend:
    labels:
      - "traefik.http.routers.${PROJECT_NAME}.rule=Host(`${SECOND_LEVEL_DOMAIN}.localhost`)"

networks:
  traefik-global-proxy:
    external: true
