---
version: "3.8"

services:
  backend:
    image: docker.io/bitnami/nginx
    container_name: ${PROJECT_NAME}
    volumes:
      - ./html:/app
    ports:
      - "${PROJECT_PORT_EXTERNAL}:8080"
    labels:
      - "traefik.enable=true"
