#!/bin/bash

# ensure the podman user service has been started
if systemctl --user list-units --all | grep -Fq podman.service | grep -Fq inactive; then
  systemctl --user start podman.service
fi

# ensure the traefik-global-proxy network exists
if ! podman network ls | grep -Fq traefik-global-proxy; then
  podman network create traefik-global-proxy
fi

# start the container
# docker-compose -H unix:$XDG_RUNTIME_DIR/podman/podman.sock -f podman-compose.yml -f docker-compose.dev.yml down
docker-compose -H unix:$XDG_RUNTIME_DIR/podman/podman.sock -f podman-compose.yml -f docker-compose.dev.yml up --remove-orphans
# RUNTIME_DIR=$XDG_RUNTIME_DIR podman-compose -f podman-compose.yml -f docker-compose.dev.yml down
# RUNTIME_DIR=$XDG_RUNTIME_DIR podman-compose -f podman-compose.yml -f docker-compose.dev.yml up --remove-orphans
