#!/bin/bash

# ensure the podman user service has been started
if systemctl --user list-units --all | grep -Fq podman.service | grep -Fq inactive; then
  systemctl --user start podman.service
fi

# start the container
# docker-compose -H unix:/run/user/$(id -u)/podman/podman.sock -f podman-compose.yml -f docker-compose.dev.yml down
# docker-compose -H unix:/run/user/$(id -u)/podman/podman.sock -f podman-compose.yml -f docker-compose.dev.yml up --remove-orphans
podman-compose -f podman-compose.yml -f docker-compose.dev.yml down
podman-compose -f podman-compose.yml -f docker-compose.dev.yml up $1
